# Generated by Django 3.2.5 on 2021-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.TextField(blank=True, null=True)),
                ('interest', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Fresh', 'Fresh'), ('Claim', 'Claim'), ('Converted', 'Converted'), ('Cancelled', 'Cancelled')], default='Fresh', max_length=50)),
            ],
        ),
    ]
